# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from custom_components.minez.bos.v1 import actions_pb2 as bos_dot_v1_dot_actions__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bos/v1/actions_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ActionsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/braiins.bos.v1.ActionsService/Start',
                request_serializer=bos_dot_v1_dot_actions__pb2.StartRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_actions__pb2.StartResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/braiins.bos.v1.ActionsService/Stop',
                request_serializer=bos_dot_v1_dot_actions__pb2.StopRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_actions__pb2.StopResponse.FromString,
                _registered_method=True)
        self.PauseMining = channel.unary_unary(
                '/braiins.bos.v1.ActionsService/PauseMining',
                request_serializer=bos_dot_v1_dot_actions__pb2.PauseMiningRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_actions__pb2.PauseMiningResponse.FromString,
                _registered_method=True)
        self.ResumeMining = channel.unary_unary(
                '/braiins.bos.v1.ActionsService/ResumeMining',
                request_serializer=bos_dot_v1_dot_actions__pb2.ResumeMiningRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_actions__pb2.ResumeMiningResponse.FromString,
                _registered_method=True)
        self.Restart = channel.unary_unary(
                '/braiins.bos.v1.ActionsService/Restart',
                request_serializer=bos_dot_v1_dot_actions__pb2.RestartRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_actions__pb2.RestartResponse.FromString,
                _registered_method=True)
        self.Reboot = channel.unary_unary(
                '/braiins.bos.v1.ActionsService/Reboot',
                request_serializer=bos_dot_v1_dot_actions__pb2.RebootRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_actions__pb2.RebootResponse.FromString,
                _registered_method=True)
        self.FactoryReset = channel.unary_unary(
                '/braiins.bos.v1.ActionsService/FactoryReset',
                request_serializer=bos_dot_v1_dot_actions__pb2.FactoryResetRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_actions__pb2.FactoryResetResponse.FromString,
                _registered_method=True)
        self.SetLocateDeviceStatus = channel.unary_unary(
                '/braiins.bos.v1.ActionsService/SetLocateDeviceStatus',
                request_serializer=bos_dot_v1_dot_actions__pb2.SetLocateDeviceStatusRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_actions__pb2.LocateDeviceStatusResponse.FromString,
                _registered_method=True)
        self.GetLocateDeviceStatus = channel.unary_unary(
                '/braiins.bos.v1.ActionsService/GetLocateDeviceStatus',
                request_serializer=bos_dot_v1_dot_actions__pb2.GetLocateDeviceStatusRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_actions__pb2.LocateDeviceStatusResponse.FromString,
                _registered_method=True)


class ActionsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """Method to start bosminer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Method to stop bosminer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseMining(self, request, context):
        """Method to pause mining
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeMining(self, request, context):
        """Method to resume mining
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Restart(self, request, context):
        """Method to restart bosminer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reboot(self, request, context):
        """Method to reboot whole miner
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FactoryReset(self, request, context):
        """Method to factory reset
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLocateDeviceStatus(self, request, context):
        """Method to enable/disable locate device mode
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLocateDeviceStatus(self, request, context):
        """Method to retrieve the locate device mode status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=bos_dot_v1_dot_actions__pb2.StartRequest.FromString,
                    response_serializer=bos_dot_v1_dot_actions__pb2.StartResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=bos_dot_v1_dot_actions__pb2.StopRequest.FromString,
                    response_serializer=bos_dot_v1_dot_actions__pb2.StopResponse.SerializeToString,
            ),
            'PauseMining': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseMining,
                    request_deserializer=bos_dot_v1_dot_actions__pb2.PauseMiningRequest.FromString,
                    response_serializer=bos_dot_v1_dot_actions__pb2.PauseMiningResponse.SerializeToString,
            ),
            'ResumeMining': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeMining,
                    request_deserializer=bos_dot_v1_dot_actions__pb2.ResumeMiningRequest.FromString,
                    response_serializer=bos_dot_v1_dot_actions__pb2.ResumeMiningResponse.SerializeToString,
            ),
            'Restart': grpc.unary_unary_rpc_method_handler(
                    servicer.Restart,
                    request_deserializer=bos_dot_v1_dot_actions__pb2.RestartRequest.FromString,
                    response_serializer=bos_dot_v1_dot_actions__pb2.RestartResponse.SerializeToString,
            ),
            'Reboot': grpc.unary_unary_rpc_method_handler(
                    servicer.Reboot,
                    request_deserializer=bos_dot_v1_dot_actions__pb2.RebootRequest.FromString,
                    response_serializer=bos_dot_v1_dot_actions__pb2.RebootResponse.SerializeToString,
            ),
            'FactoryReset': grpc.unary_unary_rpc_method_handler(
                    servicer.FactoryReset,
                    request_deserializer=bos_dot_v1_dot_actions__pb2.FactoryResetRequest.FromString,
                    response_serializer=bos_dot_v1_dot_actions__pb2.FactoryResetResponse.SerializeToString,
            ),
            'SetLocateDeviceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLocateDeviceStatus,
                    request_deserializer=bos_dot_v1_dot_actions__pb2.SetLocateDeviceStatusRequest.FromString,
                    response_serializer=bos_dot_v1_dot_actions__pb2.LocateDeviceStatusResponse.SerializeToString,
            ),
            'GetLocateDeviceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocateDeviceStatus,
                    request_deserializer=bos_dot_v1_dot_actions__pb2.GetLocateDeviceStatusRequest.FromString,
                    response_serializer=bos_dot_v1_dot_actions__pb2.LocateDeviceStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'braiins.bos.v1.ActionsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('braiins.bos.v1.ActionsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ActionsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.ActionsService/Start',
            bos_dot_v1_dot_actions__pb2.StartRequest.SerializeToString,
            bos_dot_v1_dot_actions__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.ActionsService/Stop',
            bos_dot_v1_dot_actions__pb2.StopRequest.SerializeToString,
            bos_dot_v1_dot_actions__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseMining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.ActionsService/PauseMining',
            bos_dot_v1_dot_actions__pb2.PauseMiningRequest.SerializeToString,
            bos_dot_v1_dot_actions__pb2.PauseMiningResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeMining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.ActionsService/ResumeMining',
            bos_dot_v1_dot_actions__pb2.ResumeMiningRequest.SerializeToString,
            bos_dot_v1_dot_actions__pb2.ResumeMiningResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Restart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.ActionsService/Restart',
            bos_dot_v1_dot_actions__pb2.RestartRequest.SerializeToString,
            bos_dot_v1_dot_actions__pb2.RestartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reboot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.ActionsService/Reboot',
            bos_dot_v1_dot_actions__pb2.RebootRequest.SerializeToString,
            bos_dot_v1_dot_actions__pb2.RebootResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FactoryReset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.ActionsService/FactoryReset',
            bos_dot_v1_dot_actions__pb2.FactoryResetRequest.SerializeToString,
            bos_dot_v1_dot_actions__pb2.FactoryResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLocateDeviceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.ActionsService/SetLocateDeviceStatus',
            bos_dot_v1_dot_actions__pb2.SetLocateDeviceStatusRequest.SerializeToString,
            bos_dot_v1_dot_actions__pb2.LocateDeviceStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLocateDeviceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.ActionsService/GetLocateDeviceStatus',
            bos_dot_v1_dot_actions__pb2.GetLocateDeviceStatusRequest.SerializeToString,
            bos_dot_v1_dot_actions__pb2.LocateDeviceStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
