# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from custom_components.minez.bos.v1 import configuration_pb2 as bos_dot_v1_dot_configuration__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bos/v1/configuration_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConfigurationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMinerConfiguration = channel.unary_unary(
                '/braiins.bos.v1.ConfigurationService/GetMinerConfiguration',
                request_serializer=bos_dot_v1_dot_configuration__pb2.GetMinerConfigurationRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_configuration__pb2.GetMinerConfigurationResponse.FromString,
                _registered_method=True)
        self.GetConstraints = channel.unary_unary(
                '/braiins.bos.v1.ConfigurationService/GetConstraints',
                request_serializer=bos_dot_v1_dot_configuration__pb2.GetConstraintsRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_configuration__pb2.GetConstraintsResponse.FromString,
                _registered_method=True)


class ConfigurationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMinerConfiguration(self, request, context):
        """Method to get current miner configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConstraints(self, request, context):
        """Method to get current configuration constraints(min, max, default)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConfigurationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMinerConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMinerConfiguration,
                    request_deserializer=bos_dot_v1_dot_configuration__pb2.GetMinerConfigurationRequest.FromString,
                    response_serializer=bos_dot_v1_dot_configuration__pb2.GetMinerConfigurationResponse.SerializeToString,
            ),
            'GetConstraints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConstraints,
                    request_deserializer=bos_dot_v1_dot_configuration__pb2.GetConstraintsRequest.FromString,
                    response_serializer=bos_dot_v1_dot_configuration__pb2.GetConstraintsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'braiins.bos.v1.ConfigurationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('braiins.bos.v1.ConfigurationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConfigurationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMinerConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.ConfigurationService/GetMinerConfiguration',
            bos_dot_v1_dot_configuration__pb2.GetMinerConfigurationRequest.SerializeToString,
            bos_dot_v1_dot_configuration__pb2.GetMinerConfigurationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConstraints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.ConfigurationService/GetConstraints',
            bos_dot_v1_dot_configuration__pb2.GetConstraintsRequest.SerializeToString,
            bos_dot_v1_dot_configuration__pb2.GetConstraintsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
