# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from custom_components.minez.bos.v1 import cooling_pb2 as bos_dot_v1_dot_cooling__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bos/v1/cooling_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoolingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCoolingState = channel.unary_unary(
                '/braiins.bos.v1.CoolingService/GetCoolingState',
                request_serializer=bos_dot_v1_dot_cooling__pb2.GetCoolingStateRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_cooling__pb2.GetCoolingStateResponse.FromString,
                _registered_method=True)
        self.SetImmersionMode = channel.unary_unary(
                '/braiins.bos.v1.CoolingService/SetImmersionMode',
                request_serializer=bos_dot_v1_dot_cooling__pb2.SetImmersionModeRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_cooling__pb2.SetImmersionModeResponse.FromString,
                _registered_method=True)
        self.SetCoolingMode = channel.unary_unary(
                '/braiins.bos.v1.CoolingService/SetCoolingMode',
                request_serializer=bos_dot_v1_dot_cooling__pb2.SetCoolingModeRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_cooling__pb2.SetCoolingModeResponse.FromString,
                _registered_method=True)


class CoolingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCoolingState(self, request, context):
        """Method to get current temperature measurements and fans states
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetImmersionMode(self, request, context):
        """Method to set/toggle immersion mode
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCoolingMode(self, request, context):
        """Method to set cooling mode
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoolingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCoolingState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCoolingState,
                    request_deserializer=bos_dot_v1_dot_cooling__pb2.GetCoolingStateRequest.FromString,
                    response_serializer=bos_dot_v1_dot_cooling__pb2.GetCoolingStateResponse.SerializeToString,
            ),
            'SetImmersionMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetImmersionMode,
                    request_deserializer=bos_dot_v1_dot_cooling__pb2.SetImmersionModeRequest.FromString,
                    response_serializer=bos_dot_v1_dot_cooling__pb2.SetImmersionModeResponse.SerializeToString,
            ),
            'SetCoolingMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCoolingMode,
                    request_deserializer=bos_dot_v1_dot_cooling__pb2.SetCoolingModeRequest.FromString,
                    response_serializer=bos_dot_v1_dot_cooling__pb2.SetCoolingModeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'braiins.bos.v1.CoolingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('braiins.bos.v1.CoolingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoolingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCoolingState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.CoolingService/GetCoolingState',
            bos_dot_v1_dot_cooling__pb2.GetCoolingStateRequest.SerializeToString,
            bos_dot_v1_dot_cooling__pb2.GetCoolingStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetImmersionMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.CoolingService/SetImmersionMode',
            bos_dot_v1_dot_cooling__pb2.SetImmersionModeRequest.SerializeToString,
            bos_dot_v1_dot_cooling__pb2.SetImmersionModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCoolingMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.CoolingService/SetCoolingMode',
            bos_dot_v1_dot_cooling__pb2.SetCoolingModeRequest.SerializeToString,
            bos_dot_v1_dot_cooling__pb2.SetCoolingModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
