# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bos/v1/license.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bos/v1/license.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.minez.bos.v1 import units_pb2 as bos_dot_v1_dot_units__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62os/v1/license.proto\x12\x0e\x62raiins.bos.v1\x1a\x12\x62os/v1/units.proto\")\n\x0bNoneLicense\x12\x1a\n\x12time_to_restricted\x18\x01 \x01(\r\"\x10\n\x0eLimitedLicense\"\x9a\x01\n\x0cValidLicense\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.braiins.bos.v1.LicenseType\x12\x15\n\rcontract_name\x18\x02 \x01(\t\x12\x1a\n\x12time_to_restricted\x18\x03 \x01(\r\x12,\n\x07\x64\x65v_fee\x18\x04 \x01(\x0b\x32\x1b.braiins.bos.v1.BasesPoints\"\x80\x01\n\x0e\x45xpiredLicense\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.braiins.bos.v1.LicenseType\x12\x15\n\rcontract_name\x18\x02 \x01(\t\x12,\n\x07\x64\x65v_fee\x18\x03 \x01(\x0b\x32\x1b.braiins.bos.v1.BasesPoints\"\x18\n\x16GetLicenseStateRequest\"\xe4\x01\n\x17GetLicenseStateResponse\x12+\n\x04none\x18\x01 \x01(\x0b\x32\x1b.braiins.bos.v1.NoneLicenseH\x00\x12\x31\n\x07limited\x18\x02 \x01(\x0b\x32\x1e.braiins.bos.v1.LimitedLicenseH\x00\x12-\n\x05valid\x18\x03 \x01(\x0b\x32\x1c.braiins.bos.v1.ValidLicenseH\x00\x12\x31\n\x07\x65xpired\x18\x04 \x01(\x0b\x32\x1e.braiins.bos.v1.ExpiredLicenseH\x00\x42\x07\n\x05state\"/\n\x17\x41pplyContractKeyRequest\x12\x14\n\x0c\x63ontract_key\x18\x01 \x01(\t\".\n\x18\x41pplyContractKeyResponse\x12\x12\n\nsuccessful\x18\x01 \x01(\x08*_\n\x0bLicenseType\x12\x1c\n\x18LICENSE_TYPE_UNSPECIFIED\x10\x00\x12\x19\n\x15LICENSE_TYPE_STANDARD\x10\x01\x12\x17\n\x13LICENSE_TYPE_CUSTOM\x10\x02\x32\xdb\x01\n\x0eLicenseService\x12\x62\n\x0fGetLicenseState\x12&.braiins.bos.v1.GetLicenseStateRequest\x1a\'.braiins.bos.v1.GetLicenseStateResponse\x12\x65\n\x10\x41pplyContractKey\x12\'.braiins.bos.v1.ApplyContractKeyRequest\x1a(.braiins.bos.v1.ApplyContractKeyResponseB=Z;github.com/braiins/bos-plus-api/braiins/bos/v1;bos_proto_v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bos.v1.license_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/braiins/bos-plus-api/braiins/bos/v1;bos_proto_v1'
  _globals['_LICENSETYPE']._serialized_start=763
  _globals['_LICENSETYPE']._serialized_end=858
  _globals['_NONELICENSE']._serialized_start=60
  _globals['_NONELICENSE']._serialized_end=101
  _globals['_LIMITEDLICENSE']._serialized_start=103
  _globals['_LIMITEDLICENSE']._serialized_end=119
  _globals['_VALIDLICENSE']._serialized_start=122
  _globals['_VALIDLICENSE']._serialized_end=276
  _globals['_EXPIREDLICENSE']._serialized_start=279
  _globals['_EXPIREDLICENSE']._serialized_end=407
  _globals['_GETLICENSESTATEREQUEST']._serialized_start=409
  _globals['_GETLICENSESTATEREQUEST']._serialized_end=433
  _globals['_GETLICENSESTATERESPONSE']._serialized_start=436
  _globals['_GETLICENSESTATERESPONSE']._serialized_end=664
  _globals['_APPLYCONTRACTKEYREQUEST']._serialized_start=666
  _globals['_APPLYCONTRACTKEYREQUEST']._serialized_end=713
  _globals['_APPLYCONTRACTKEYRESPONSE']._serialized_start=715
  _globals['_APPLYCONTRACTKEYRESPONSE']._serialized_end=761
  _globals['_LICENSESERVICE']._serialized_start=861
  _globals['_LICENSESERVICE']._serialized_end=1080
# @@protoc_insertion_point(module_scope)
