# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from custom_components.minez.bos.v1 import license_pb2 as bos_dot_v1_dot_license__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bos/v1/license_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LicenseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLicenseState = channel.unary_unary(
                '/braiins.bos.v1.LicenseService/GetLicenseState',
                request_serializer=bos_dot_v1_dot_license__pb2.GetLicenseStateRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_license__pb2.GetLicenseStateResponse.FromString,
                _registered_method=True)
        self.ApplyContractKey = channel.unary_unary(
                '/braiins.bos.v1.LicenseService/ApplyContractKey',
                request_serializer=bos_dot_v1_dot_license__pb2.ApplyContractKeyRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_license__pb2.ApplyContractKeyResponse.FromString,
                _registered_method=True)


class LicenseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLicenseState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyContractKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LicenseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLicenseState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLicenseState,
                    request_deserializer=bos_dot_v1_dot_license__pb2.GetLicenseStateRequest.FromString,
                    response_serializer=bos_dot_v1_dot_license__pb2.GetLicenseStateResponse.SerializeToString,
            ),
            'ApplyContractKey': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyContractKey,
                    request_deserializer=bos_dot_v1_dot_license__pb2.ApplyContractKeyRequest.FromString,
                    response_serializer=bos_dot_v1_dot_license__pb2.ApplyContractKeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'braiins.bos.v1.LicenseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('braiins.bos.v1.LicenseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LicenseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLicenseState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.LicenseService/GetLicenseState',
            bos_dot_v1_dot_license__pb2.GetLicenseStateRequest.SerializeToString,
            bos_dot_v1_dot_license__pb2.GetLicenseStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyContractKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.LicenseService/ApplyContractKey',
            bos_dot_v1_dot_license__pb2.ApplyContractKeyRequest.SerializeToString,
            bos_dot_v1_dot_license__pb2.ApplyContractKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
