# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from custom_components.minez.bos.v1 import miner_pb2 as bos_dot_v1_dot_miner__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bos/v1/miner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MinerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMinerStatus = channel.unary_stream(
                '/braiins.bos.v1.MinerService/GetMinerStatus',
                request_serializer=bos_dot_v1_dot_miner__pb2.GetMinerStatusRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_miner__pb2.GetMinerStatusResponse.FromString,
                _registered_method=True)
        self.GetMinerDetails = channel.unary_unary(
                '/braiins.bos.v1.MinerService/GetMinerDetails',
                request_serializer=bos_dot_v1_dot_miner__pb2.GetMinerDetailsRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_miner__pb2.GetMinerDetailsResponse.FromString,
                _registered_method=True)
        self.GetMinerStats = channel.unary_unary(
                '/braiins.bos.v1.MinerService/GetMinerStats',
                request_serializer=bos_dot_v1_dot_miner__pb2.GetMinerStatsRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_miner__pb2.GetMinerStatsResponse.FromString,
                _registered_method=True)
        self.GetErrors = channel.unary_unary(
                '/braiins.bos.v1.MinerService/GetErrors',
                request_serializer=bos_dot_v1_dot_miner__pb2.GetErrorsRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_miner__pb2.GetErrorsResponse.FromString,
                _registered_method=True)
        self.GetHashboards = channel.unary_unary(
                '/braiins.bos.v1.MinerService/GetHashboards',
                request_serializer=bos_dot_v1_dot_miner__pb2.GetHashboardsRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_miner__pb2.GetHashboardsResponse.FromString,
                _registered_method=True)
        self.GetSupportArchive = channel.unary_stream(
                '/braiins.bos.v1.MinerService/GetSupportArchive',
                request_serializer=bos_dot_v1_dot_miner__pb2.GetSupportArchiveRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_miner__pb2.GetSupportArchiveResponse.FromString,
                _registered_method=True)
        self.EnableHashboards = channel.unary_unary(
                '/braiins.bos.v1.MinerService/EnableHashboards',
                request_serializer=bos_dot_v1_dot_miner__pb2.EnableHashboardsRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_miner__pb2.EnableHashboardsResponse.FromString,
                _registered_method=True)
        self.DisableHashboards = channel.unary_unary(
                '/braiins.bos.v1.MinerService/DisableHashboards',
                request_serializer=bos_dot_v1_dot_miner__pb2.DisableHashboardsRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_miner__pb2.DisableHashboardsResponse.FromString,
                _registered_method=True)


class MinerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMinerStatus(self, request, context):
        """Method to fetch miner status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMinerDetails(self, request, context):
        """Method to get miner details.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMinerStats(self, request, context):
        """Method to get aggregated miner stats.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetErrors(self, request, context):
        """Method to get miner errors
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHashboards(self, request, context):
        """Method to get miner hashboards state and statistics.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSupportArchive(self, request, context):
        """Method to download BOS support archive
        Method returns stream of messages with binary chunks that needs to be concatenated on the caller side
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableHashboards(self, request, context):
        """Method to enable hashboards
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableHashboards(self, request, context):
        """Method to disable hashboards
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MinerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMinerStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMinerStatus,
                    request_deserializer=bos_dot_v1_dot_miner__pb2.GetMinerStatusRequest.FromString,
                    response_serializer=bos_dot_v1_dot_miner__pb2.GetMinerStatusResponse.SerializeToString,
            ),
            'GetMinerDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMinerDetails,
                    request_deserializer=bos_dot_v1_dot_miner__pb2.GetMinerDetailsRequest.FromString,
                    response_serializer=bos_dot_v1_dot_miner__pb2.GetMinerDetailsResponse.SerializeToString,
            ),
            'GetMinerStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMinerStats,
                    request_deserializer=bos_dot_v1_dot_miner__pb2.GetMinerStatsRequest.FromString,
                    response_serializer=bos_dot_v1_dot_miner__pb2.GetMinerStatsResponse.SerializeToString,
            ),
            'GetErrors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetErrors,
                    request_deserializer=bos_dot_v1_dot_miner__pb2.GetErrorsRequest.FromString,
                    response_serializer=bos_dot_v1_dot_miner__pb2.GetErrorsResponse.SerializeToString,
            ),
            'GetHashboards': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHashboards,
                    request_deserializer=bos_dot_v1_dot_miner__pb2.GetHashboardsRequest.FromString,
                    response_serializer=bos_dot_v1_dot_miner__pb2.GetHashboardsResponse.SerializeToString,
            ),
            'GetSupportArchive': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSupportArchive,
                    request_deserializer=bos_dot_v1_dot_miner__pb2.GetSupportArchiveRequest.FromString,
                    response_serializer=bos_dot_v1_dot_miner__pb2.GetSupportArchiveResponse.SerializeToString,
            ),
            'EnableHashboards': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableHashboards,
                    request_deserializer=bos_dot_v1_dot_miner__pb2.EnableHashboardsRequest.FromString,
                    response_serializer=bos_dot_v1_dot_miner__pb2.EnableHashboardsResponse.SerializeToString,
            ),
            'DisableHashboards': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableHashboards,
                    request_deserializer=bos_dot_v1_dot_miner__pb2.DisableHashboardsRequest.FromString,
                    response_serializer=bos_dot_v1_dot_miner__pb2.DisableHashboardsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'braiins.bos.v1.MinerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('braiins.bos.v1.MinerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MinerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMinerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/braiins.bos.v1.MinerService/GetMinerStatus',
            bos_dot_v1_dot_miner__pb2.GetMinerStatusRequest.SerializeToString,
            bos_dot_v1_dot_miner__pb2.GetMinerStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMinerDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.MinerService/GetMinerDetails',
            bos_dot_v1_dot_miner__pb2.GetMinerDetailsRequest.SerializeToString,
            bos_dot_v1_dot_miner__pb2.GetMinerDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMinerStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.MinerService/GetMinerStats',
            bos_dot_v1_dot_miner__pb2.GetMinerStatsRequest.SerializeToString,
            bos_dot_v1_dot_miner__pb2.GetMinerStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetErrors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.MinerService/GetErrors',
            bos_dot_v1_dot_miner__pb2.GetErrorsRequest.SerializeToString,
            bos_dot_v1_dot_miner__pb2.GetErrorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHashboards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.MinerService/GetHashboards',
            bos_dot_v1_dot_miner__pb2.GetHashboardsRequest.SerializeToString,
            bos_dot_v1_dot_miner__pb2.GetHashboardsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSupportArchive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/braiins.bos.v1.MinerService/GetSupportArchive',
            bos_dot_v1_dot_miner__pb2.GetSupportArchiveRequest.SerializeToString,
            bos_dot_v1_dot_miner__pb2.GetSupportArchiveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnableHashboards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.MinerService/EnableHashboards',
            bos_dot_v1_dot_miner__pb2.EnableHashboardsRequest.SerializeToString,
            bos_dot_v1_dot_miner__pb2.EnableHashboardsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableHashboards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.MinerService/DisableHashboards',
            bos_dot_v1_dot_miner__pb2.DisableHashboardsRequest.SerializeToString,
            bos_dot_v1_dot_miner__pb2.DisableHashboardsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
