# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from custom_components.minez.bos.v1 import network_pb2 as bos_dot_v1_dot_network__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bos/v1/network_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NetworkServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNetworkConfiguration = channel.unary_unary(
                '/braiins.bos.v1.NetworkService/GetNetworkConfiguration',
                request_serializer=bos_dot_v1_dot_network__pb2.GetNetworkConfigurationRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_network__pb2.GetNetworkConfigurationResponse.FromString,
                _registered_method=True)
        self.SetNetworkConfiguration = channel.unary_unary(
                '/braiins.bos.v1.NetworkService/SetNetworkConfiguration',
                request_serializer=bos_dot_v1_dot_network__pb2.SetNetworkConfigurationRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_network__pb2.SetNetworkConfigurationResponse.FromString,
                _registered_method=True)
        self.GetNetworkInfo = channel.unary_unary(
                '/braiins.bos.v1.NetworkService/GetNetworkInfo',
                request_serializer=bos_dot_v1_dot_network__pb2.GetNetworkInfoRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_network__pb2.GetNetworkInfoResponse.FromString,
                _registered_method=True)


class NetworkServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetNetworkConfiguration(self, request, context):
        """Method to get network configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetNetworkConfiguration(self, request, context):
        """Method to set network configuration. You can specify protocol or hostname, or both.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNetworkInfo(self, request, context):
        """Method to get current network configuration for the default network interface
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NetworkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNetworkConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetworkConfiguration,
                    request_deserializer=bos_dot_v1_dot_network__pb2.GetNetworkConfigurationRequest.FromString,
                    response_serializer=bos_dot_v1_dot_network__pb2.GetNetworkConfigurationResponse.SerializeToString,
            ),
            'SetNetworkConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.SetNetworkConfiguration,
                    request_deserializer=bos_dot_v1_dot_network__pb2.SetNetworkConfigurationRequest.FromString,
                    response_serializer=bos_dot_v1_dot_network__pb2.SetNetworkConfigurationResponse.SerializeToString,
            ),
            'GetNetworkInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetworkInfo,
                    request_deserializer=bos_dot_v1_dot_network__pb2.GetNetworkInfoRequest.FromString,
                    response_serializer=bos_dot_v1_dot_network__pb2.GetNetworkInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'braiins.bos.v1.NetworkService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('braiins.bos.v1.NetworkService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NetworkService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetNetworkConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.NetworkService/GetNetworkConfiguration',
            bos_dot_v1_dot_network__pb2.GetNetworkConfigurationRequest.SerializeToString,
            bos_dot_v1_dot_network__pb2.GetNetworkConfigurationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetNetworkConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.NetworkService/SetNetworkConfiguration',
            bos_dot_v1_dot_network__pb2.SetNetworkConfigurationRequest.SerializeToString,
            bos_dot_v1_dot_network__pb2.SetNetworkConfigurationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNetworkInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.NetworkService/GetNetworkInfo',
            bos_dot_v1_dot_network__pb2.GetNetworkInfoRequest.SerializeToString,
            bos_dot_v1_dot_network__pb2.GetNetworkInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
