# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from custom_components.minez.bos.v1 import performance_pb2 as bos_dot_v1_dot_performance__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bos/v1/performance_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PerformanceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTunerState = channel.unary_unary(
                '/braiins.bos.v1.PerformanceService/GetTunerState',
                request_serializer=bos_dot_v1_dot_performance__pb2.GetTunerStateRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_performance__pb2.GetTunerStateResponse.FromString,
                _registered_method=True)
        self.ListTargetProfiles = channel.unary_unary(
                '/braiins.bos.v1.PerformanceService/ListTargetProfiles',
                request_serializer=bos_dot_v1_dot_performance__pb2.ListTargetProfilesRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_performance__pb2.ListTargetProfilesResponse.FromString,
                _registered_method=True)
        self.SetDefaultPowerTarget = channel.unary_unary(
                '/braiins.bos.v1.PerformanceService/SetDefaultPowerTarget',
                request_serializer=bos_dot_v1_dot_performance__pb2.SetDefaultPowerTargetRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_performance__pb2.SetPowerTargetResponse.FromString,
                _registered_method=True)
        self.SetPowerTarget = channel.unary_unary(
                '/braiins.bos.v1.PerformanceService/SetPowerTarget',
                request_serializer=bos_dot_v1_dot_performance__pb2.SetPowerTargetRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_performance__pb2.SetPowerTargetResponse.FromString,
                _registered_method=True)
        self.IncrementPowerTarget = channel.unary_unary(
                '/braiins.bos.v1.PerformanceService/IncrementPowerTarget',
                request_serializer=bos_dot_v1_dot_performance__pb2.IncrementPowerTargetRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_performance__pb2.SetPowerTargetResponse.FromString,
                _registered_method=True)
        self.DecrementPowerTarget = channel.unary_unary(
                '/braiins.bos.v1.PerformanceService/DecrementPowerTarget',
                request_serializer=bos_dot_v1_dot_performance__pb2.DecrementPowerTargetRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_performance__pb2.SetPowerTargetResponse.FromString,
                _registered_method=True)
        self.SetRelativePowerTarget = channel.unary_unary(
                '/braiins.bos.v1.PerformanceService/SetRelativePowerTarget',
                request_serializer=bos_dot_v1_dot_performance__pb2.SetRelativeTargetRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_performance__pb2.SetPowerTargetResponse.FromString,
                _registered_method=True)
        self.SetDefaultHashrateTarget = channel.unary_unary(
                '/braiins.bos.v1.PerformanceService/SetDefaultHashrateTarget',
                request_serializer=bos_dot_v1_dot_performance__pb2.SetDefaultHashrateTargetRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_performance__pb2.SetHashrateTargetResponse.FromString,
                _registered_method=True)
        self.SetHashrateTarget = channel.unary_unary(
                '/braiins.bos.v1.PerformanceService/SetHashrateTarget',
                request_serializer=bos_dot_v1_dot_performance__pb2.SetHashrateTargetRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_performance__pb2.SetHashrateTargetResponse.FromString,
                _registered_method=True)
        self.IncrementHashrateTarget = channel.unary_unary(
                '/braiins.bos.v1.PerformanceService/IncrementHashrateTarget',
                request_serializer=bos_dot_v1_dot_performance__pb2.IncrementHashrateTargetRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_performance__pb2.SetHashrateTargetResponse.FromString,
                _registered_method=True)
        self.DecrementHashrateTarget = channel.unary_unary(
                '/braiins.bos.v1.PerformanceService/DecrementHashrateTarget',
                request_serializer=bos_dot_v1_dot_performance__pb2.DecrementHashrateTargetRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_performance__pb2.SetHashrateTargetResponse.FromString,
                _registered_method=True)
        self.SetRelativeHashrateTarget = channel.unary_unary(
                '/braiins.bos.v1.PerformanceService/SetRelativeHashrateTarget',
                request_serializer=bos_dot_v1_dot_performance__pb2.SetRelativeTargetRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_performance__pb2.SetHashrateTargetResponse.FromString,
                _registered_method=True)
        self.SetDPS = channel.unary_unary(
                '/braiins.bos.v1.PerformanceService/SetDPS',
                request_serializer=bos_dot_v1_dot_performance__pb2.SetDPSRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_performance__pb2.SetDPSResponse.FromString,
                _registered_method=True)
        self.SetPerformanceMode = channel.unary_unary(
                '/braiins.bos.v1.PerformanceService/SetPerformanceMode',
                request_serializer=bos_dot_v1_dot_performance__pb2.SetPerformanceModeRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_performance__pb2.PerformanceMode.FromString,
                _registered_method=True)
        self.GetActivePerformanceMode = channel.unary_unary(
                '/braiins.bos.v1.PerformanceService/GetActivePerformanceMode',
                request_serializer=bos_dot_v1_dot_performance__pb2.GetPerformanceModeRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_performance__pb2.PerformanceMode.FromString,
                _registered_method=True)
        self.RemoveTunedProfiles = channel.unary_unary(
                '/braiins.bos.v1.PerformanceService/RemoveTunedProfiles',
                request_serializer=bos_dot_v1_dot_performance__pb2.RemoveTunedProfilesRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_performance__pb2.RemoveTunedProfilesResponse.FromString,
                _registered_method=True)
        self.SetQuickRamping = channel.unary_unary(
                '/braiins.bos.v1.PerformanceService/SetQuickRamping',
                request_serializer=bos_dot_v1_dot_performance__pb2.SetQuickRampingRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_performance__pb2.QuickRampingResponse.FromString,
                _registered_method=True)
        self.SetDefaultQuickRamping = channel.unary_unary(
                '/braiins.bos.v1.PerformanceService/SetDefaultQuickRamping',
                request_serializer=bos_dot_v1_dot_performance__pb2.SetDefaultQuickRampingRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_performance__pb2.QuickRampingResponse.FromString,
                _registered_method=True)


class PerformanceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTunerState(self, request, context):
        """Method to get the current tuner details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTargetProfiles(self, request, context):
        """Method to get the current tuner details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDefaultPowerTarget(self, request, context):
        """Method to set default power target for tuner
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPowerTarget(self, request, context):
        """Method to set absolute power target for tuner
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncrementPowerTarget(self, request, context):
        """Method to increment power target for tuner
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecrementPowerTarget(self, request, context):
        """Method to decrement power target for tuner
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRelativePowerTarget(self, request, context):
        """Method to set power target relative to a reference value
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDefaultHashrateTarget(self, request, context):
        """Method to set default hashrate target for tuner
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetHashrateTarget(self, request, context):
        """Method to set absolute hashrate target for tuner
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncrementHashrateTarget(self, request, context):
        """Method to increment hashrate target for tuner
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecrementHashrateTarget(self, request, context):
        """Method to decrement hashrate target for tuner
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRelativeHashrateTarget(self, request, context):
        """Method to set hashrate target relative to a reference value
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDPS(self, request, context):
        """Method to set Dynamic Performance Scaling
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPerformanceMode(self, request, context):
        """Method to set performance mode
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActivePerformanceMode(self, request, context):
        """Method to read active(runtime) performance mode
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveTunedProfiles(self, request, context):
        """Method to remove tuned profiles
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetQuickRamping(self, request, context):
        """Method to set quick ramping (used in curtailments)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDefaultQuickRamping(self, request, context):
        """Method to set default quick ramping (used in curtailments)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PerformanceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTunerState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTunerState,
                    request_deserializer=bos_dot_v1_dot_performance__pb2.GetTunerStateRequest.FromString,
                    response_serializer=bos_dot_v1_dot_performance__pb2.GetTunerStateResponse.SerializeToString,
            ),
            'ListTargetProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTargetProfiles,
                    request_deserializer=bos_dot_v1_dot_performance__pb2.ListTargetProfilesRequest.FromString,
                    response_serializer=bos_dot_v1_dot_performance__pb2.ListTargetProfilesResponse.SerializeToString,
            ),
            'SetDefaultPowerTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDefaultPowerTarget,
                    request_deserializer=bos_dot_v1_dot_performance__pb2.SetDefaultPowerTargetRequest.FromString,
                    response_serializer=bos_dot_v1_dot_performance__pb2.SetPowerTargetResponse.SerializeToString,
            ),
            'SetPowerTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPowerTarget,
                    request_deserializer=bos_dot_v1_dot_performance__pb2.SetPowerTargetRequest.FromString,
                    response_serializer=bos_dot_v1_dot_performance__pb2.SetPowerTargetResponse.SerializeToString,
            ),
            'IncrementPowerTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.IncrementPowerTarget,
                    request_deserializer=bos_dot_v1_dot_performance__pb2.IncrementPowerTargetRequest.FromString,
                    response_serializer=bos_dot_v1_dot_performance__pb2.SetPowerTargetResponse.SerializeToString,
            ),
            'DecrementPowerTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.DecrementPowerTarget,
                    request_deserializer=bos_dot_v1_dot_performance__pb2.DecrementPowerTargetRequest.FromString,
                    response_serializer=bos_dot_v1_dot_performance__pb2.SetPowerTargetResponse.SerializeToString,
            ),
            'SetRelativePowerTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRelativePowerTarget,
                    request_deserializer=bos_dot_v1_dot_performance__pb2.SetRelativeTargetRequest.FromString,
                    response_serializer=bos_dot_v1_dot_performance__pb2.SetPowerTargetResponse.SerializeToString,
            ),
            'SetDefaultHashrateTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDefaultHashrateTarget,
                    request_deserializer=bos_dot_v1_dot_performance__pb2.SetDefaultHashrateTargetRequest.FromString,
                    response_serializer=bos_dot_v1_dot_performance__pb2.SetHashrateTargetResponse.SerializeToString,
            ),
            'SetHashrateTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.SetHashrateTarget,
                    request_deserializer=bos_dot_v1_dot_performance__pb2.SetHashrateTargetRequest.FromString,
                    response_serializer=bos_dot_v1_dot_performance__pb2.SetHashrateTargetResponse.SerializeToString,
            ),
            'IncrementHashrateTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.IncrementHashrateTarget,
                    request_deserializer=bos_dot_v1_dot_performance__pb2.IncrementHashrateTargetRequest.FromString,
                    response_serializer=bos_dot_v1_dot_performance__pb2.SetHashrateTargetResponse.SerializeToString,
            ),
            'DecrementHashrateTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.DecrementHashrateTarget,
                    request_deserializer=bos_dot_v1_dot_performance__pb2.DecrementHashrateTargetRequest.FromString,
                    response_serializer=bos_dot_v1_dot_performance__pb2.SetHashrateTargetResponse.SerializeToString,
            ),
            'SetRelativeHashrateTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRelativeHashrateTarget,
                    request_deserializer=bos_dot_v1_dot_performance__pb2.SetRelativeTargetRequest.FromString,
                    response_serializer=bos_dot_v1_dot_performance__pb2.SetHashrateTargetResponse.SerializeToString,
            ),
            'SetDPS': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDPS,
                    request_deserializer=bos_dot_v1_dot_performance__pb2.SetDPSRequest.FromString,
                    response_serializer=bos_dot_v1_dot_performance__pb2.SetDPSResponse.SerializeToString,
            ),
            'SetPerformanceMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPerformanceMode,
                    request_deserializer=bos_dot_v1_dot_performance__pb2.SetPerformanceModeRequest.FromString,
                    response_serializer=bos_dot_v1_dot_performance__pb2.PerformanceMode.SerializeToString,
            ),
            'GetActivePerformanceMode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActivePerformanceMode,
                    request_deserializer=bos_dot_v1_dot_performance__pb2.GetPerformanceModeRequest.FromString,
                    response_serializer=bos_dot_v1_dot_performance__pb2.PerformanceMode.SerializeToString,
            ),
            'RemoveTunedProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveTunedProfiles,
                    request_deserializer=bos_dot_v1_dot_performance__pb2.RemoveTunedProfilesRequest.FromString,
                    response_serializer=bos_dot_v1_dot_performance__pb2.RemoveTunedProfilesResponse.SerializeToString,
            ),
            'SetQuickRamping': grpc.unary_unary_rpc_method_handler(
                    servicer.SetQuickRamping,
                    request_deserializer=bos_dot_v1_dot_performance__pb2.SetQuickRampingRequest.FromString,
                    response_serializer=bos_dot_v1_dot_performance__pb2.QuickRampingResponse.SerializeToString,
            ),
            'SetDefaultQuickRamping': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDefaultQuickRamping,
                    request_deserializer=bos_dot_v1_dot_performance__pb2.SetDefaultQuickRampingRequest.FromString,
                    response_serializer=bos_dot_v1_dot_performance__pb2.QuickRampingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'braiins.bos.v1.PerformanceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('braiins.bos.v1.PerformanceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PerformanceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTunerState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.PerformanceService/GetTunerState',
            bos_dot_v1_dot_performance__pb2.GetTunerStateRequest.SerializeToString,
            bos_dot_v1_dot_performance__pb2.GetTunerStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTargetProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.PerformanceService/ListTargetProfiles',
            bos_dot_v1_dot_performance__pb2.ListTargetProfilesRequest.SerializeToString,
            bos_dot_v1_dot_performance__pb2.ListTargetProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDefaultPowerTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.PerformanceService/SetDefaultPowerTarget',
            bos_dot_v1_dot_performance__pb2.SetDefaultPowerTargetRequest.SerializeToString,
            bos_dot_v1_dot_performance__pb2.SetPowerTargetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPowerTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.PerformanceService/SetPowerTarget',
            bos_dot_v1_dot_performance__pb2.SetPowerTargetRequest.SerializeToString,
            bos_dot_v1_dot_performance__pb2.SetPowerTargetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IncrementPowerTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.PerformanceService/IncrementPowerTarget',
            bos_dot_v1_dot_performance__pb2.IncrementPowerTargetRequest.SerializeToString,
            bos_dot_v1_dot_performance__pb2.SetPowerTargetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecrementPowerTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.PerformanceService/DecrementPowerTarget',
            bos_dot_v1_dot_performance__pb2.DecrementPowerTargetRequest.SerializeToString,
            bos_dot_v1_dot_performance__pb2.SetPowerTargetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRelativePowerTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.PerformanceService/SetRelativePowerTarget',
            bos_dot_v1_dot_performance__pb2.SetRelativeTargetRequest.SerializeToString,
            bos_dot_v1_dot_performance__pb2.SetPowerTargetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDefaultHashrateTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.PerformanceService/SetDefaultHashrateTarget',
            bos_dot_v1_dot_performance__pb2.SetDefaultHashrateTargetRequest.SerializeToString,
            bos_dot_v1_dot_performance__pb2.SetHashrateTargetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetHashrateTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.PerformanceService/SetHashrateTarget',
            bos_dot_v1_dot_performance__pb2.SetHashrateTargetRequest.SerializeToString,
            bos_dot_v1_dot_performance__pb2.SetHashrateTargetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IncrementHashrateTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.PerformanceService/IncrementHashrateTarget',
            bos_dot_v1_dot_performance__pb2.IncrementHashrateTargetRequest.SerializeToString,
            bos_dot_v1_dot_performance__pb2.SetHashrateTargetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecrementHashrateTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.PerformanceService/DecrementHashrateTarget',
            bos_dot_v1_dot_performance__pb2.DecrementHashrateTargetRequest.SerializeToString,
            bos_dot_v1_dot_performance__pb2.SetHashrateTargetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRelativeHashrateTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.PerformanceService/SetRelativeHashrateTarget',
            bos_dot_v1_dot_performance__pb2.SetRelativeTargetRequest.SerializeToString,
            bos_dot_v1_dot_performance__pb2.SetHashrateTargetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDPS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.PerformanceService/SetDPS',
            bos_dot_v1_dot_performance__pb2.SetDPSRequest.SerializeToString,
            bos_dot_v1_dot_performance__pb2.SetDPSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPerformanceMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.PerformanceService/SetPerformanceMode',
            bos_dot_v1_dot_performance__pb2.SetPerformanceModeRequest.SerializeToString,
            bos_dot_v1_dot_performance__pb2.PerformanceMode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActivePerformanceMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.PerformanceService/GetActivePerformanceMode',
            bos_dot_v1_dot_performance__pb2.GetPerformanceModeRequest.SerializeToString,
            bos_dot_v1_dot_performance__pb2.PerformanceMode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveTunedProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.PerformanceService/RemoveTunedProfiles',
            bos_dot_v1_dot_performance__pb2.RemoveTunedProfilesRequest.SerializeToString,
            bos_dot_v1_dot_performance__pb2.RemoveTunedProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetQuickRamping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.PerformanceService/SetQuickRamping',
            bos_dot_v1_dot_performance__pb2.SetQuickRampingRequest.SerializeToString,
            bos_dot_v1_dot_performance__pb2.QuickRampingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDefaultQuickRamping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.PerformanceService/SetDefaultQuickRamping',
            bos_dot_v1_dot_performance__pb2.SetDefaultQuickRampingRequest.SerializeToString,
            bos_dot_v1_dot_performance__pb2.QuickRampingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
