# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from custom_components.minez.bos.v1 import pool_pb2 as bos_dot_v1_dot_pool__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bos/v1/pool_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PoolServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPoolGroups = channel.unary_unary(
                '/braiins.bos.v1.PoolService/GetPoolGroups',
                request_serializer=bos_dot_v1_dot_pool__pb2.GetPoolGroupsRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_pool__pb2.GetPoolGroupsResponse.FromString,
                _registered_method=True)
        self.CreatePoolGroup = channel.unary_unary(
                '/braiins.bos.v1.PoolService/CreatePoolGroup',
                request_serializer=bos_dot_v1_dot_pool__pb2.CreatePoolGroupRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_pool__pb2.CreatePoolGroupResponse.FromString,
                _registered_method=True)
        self.UpdatePoolGroup = channel.unary_unary(
                '/braiins.bos.v1.PoolService/UpdatePoolGroup',
                request_serializer=bos_dot_v1_dot_pool__pb2.UpdatePoolGroupRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_pool__pb2.UpdatePoolGroupResponse.FromString,
                _registered_method=True)
        self.RemovePoolGroup = channel.unary_unary(
                '/braiins.bos.v1.PoolService/RemovePoolGroup',
                request_serializer=bos_dot_v1_dot_pool__pb2.RemovePoolGroupRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_pool__pb2.RemovePoolGroupResponse.FromString,
                _registered_method=True)
        self.SetPoolGroups = channel.unary_unary(
                '/braiins.bos.v1.PoolService/SetPoolGroups',
                request_serializer=bos_dot_v1_dot_pool__pb2.SetPoolGroupsRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_pool__pb2.SetPoolGroupsResponse.FromString,
                _registered_method=True)


class PoolServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPoolGroups(self, request, context):
        """Read method to get current pool groups data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePoolGroup(self, request, context):
        """Method to create pool group
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePoolGroup(self, request, context):
        """Method to update pool group
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemovePoolGroup(self, request, context):
        """Method to remove pool group
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPoolGroups(self, request, context):
        """Method to set pool groups. Existing pool groups will be completely replaced with new groups.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PoolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPoolGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoolGroups,
                    request_deserializer=bos_dot_v1_dot_pool__pb2.GetPoolGroupsRequest.FromString,
                    response_serializer=bos_dot_v1_dot_pool__pb2.GetPoolGroupsResponse.SerializeToString,
            ),
            'CreatePoolGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePoolGroup,
                    request_deserializer=bos_dot_v1_dot_pool__pb2.CreatePoolGroupRequest.FromString,
                    response_serializer=bos_dot_v1_dot_pool__pb2.CreatePoolGroupResponse.SerializeToString,
            ),
            'UpdatePoolGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePoolGroup,
                    request_deserializer=bos_dot_v1_dot_pool__pb2.UpdatePoolGroupRequest.FromString,
                    response_serializer=bos_dot_v1_dot_pool__pb2.UpdatePoolGroupResponse.SerializeToString,
            ),
            'RemovePoolGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.RemovePoolGroup,
                    request_deserializer=bos_dot_v1_dot_pool__pb2.RemovePoolGroupRequest.FromString,
                    response_serializer=bos_dot_v1_dot_pool__pb2.RemovePoolGroupResponse.SerializeToString,
            ),
            'SetPoolGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPoolGroups,
                    request_deserializer=bos_dot_v1_dot_pool__pb2.SetPoolGroupsRequest.FromString,
                    response_serializer=bos_dot_v1_dot_pool__pb2.SetPoolGroupsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'braiins.bos.v1.PoolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('braiins.bos.v1.PoolService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PoolService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPoolGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.PoolService/GetPoolGroups',
            bos_dot_v1_dot_pool__pb2.GetPoolGroupsRequest.SerializeToString,
            bos_dot_v1_dot_pool__pb2.GetPoolGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePoolGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.PoolService/CreatePoolGroup',
            bos_dot_v1_dot_pool__pb2.CreatePoolGroupRequest.SerializeToString,
            bos_dot_v1_dot_pool__pb2.CreatePoolGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePoolGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.PoolService/UpdatePoolGroup',
            bos_dot_v1_dot_pool__pb2.UpdatePoolGroupRequest.SerializeToString,
            bos_dot_v1_dot_pool__pb2.UpdatePoolGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemovePoolGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.PoolService/RemovePoolGroup',
            bos_dot_v1_dot_pool__pb2.RemovePoolGroupRequest.SerializeToString,
            bos_dot_v1_dot_pool__pb2.RemovePoolGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPoolGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.PoolService/SetPoolGroups',
            bos_dot_v1_dot_pool__pb2.SetPoolGroupsRequest.SerializeToString,
            bos_dot_v1_dot_pool__pb2.SetPoolGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
