# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bos/v1/units.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bos/v1/units.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x62os/v1/units.proto\x12\x0e\x62raiins.bos.v1\"+\n\x0cMegaHashrate\x12\x1b\n\x13megahash_per_second\x18\x01 \x01(\x01\"+\n\x0cGigaHashrate\x12\x1b\n\x13gigahash_per_second\x18\x01 \x01(\x01\"+\n\x0cTeraHashrate\x12\x1b\n\x13terahash_per_second\x18\x01 \x01(\x01\"\x1a\n\tFrequency\x12\r\n\x05hertz\x18\x01 \x01(\x01\"\x17\n\x07Voltage\x12\x0c\n\x04volt\x18\x01 \x01(\x01\"\x15\n\x05Power\x12\x0c\n\x04watt\x18\x01 \x01(\x04\"-\n\x0fPowerEfficiency\x12\x1a\n\x12joule_per_terahash\x18\x01 \x01(\x01\"\x1f\n\x0bTemperature\x12\x10\n\x08\x64\x65gree_c\x18\x01 \x01(\x01\"\x1a\n\x0b\x42\x61sesPoints\x12\x0b\n\x03\x62sp\x18\x01 \x01(\r\"\x16\n\x05Hours\x12\r\n\x05hours\x18\x01 \x01(\r*\xd8\x01\n\tDayOfWeek\x12\x1b\n\x17\x44\x41Y_OF_WEEK_UNSPECIFIED\x10\x00\x12\x16\n\x12\x44\x41Y_OF_WEEK_MONDAY\x10\x01\x12\x17\n\x13\x44\x41Y_OF_WEEK_TUESDAY\x10\x02\x12\x19\n\x15\x44\x41Y_OF_WEEK_WEDNESDAY\x10\x03\x12\x18\n\x14\x44\x41Y_OF_WEEK_THURSDAY\x10\x04\x12\x16\n\x12\x44\x41Y_OF_WEEK_FRIDAY\x10\x05\x12\x18\n\x14\x44\x41Y_OF_WEEK_SATURDAY\x10\x06\x12\x16\n\x12\x44\x41Y_OF_WEEK_SUNDAY\x10\x07\x42=Z;github.com/braiins/bos-plus-api/braiins/bos/v1;bos_proto_v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bos.v1.units_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/braiins/bos-plus-api/braiins/bos/v1;bos_proto_v1'
  _globals['_DAYOFWEEK']._serialized_start=382
  _globals['_DAYOFWEEK']._serialized_end=598
  _globals['_MEGAHASHRATE']._serialized_start=38
  _globals['_MEGAHASHRATE']._serialized_end=81
  _globals['_GIGAHASHRATE']._serialized_start=83
  _globals['_GIGAHASHRATE']._serialized_end=126
  _globals['_TERAHASHRATE']._serialized_start=128
  _globals['_TERAHASHRATE']._serialized_end=171
  _globals['_FREQUENCY']._serialized_start=173
  _globals['_FREQUENCY']._serialized_end=199
  _globals['_VOLTAGE']._serialized_start=201
  _globals['_VOLTAGE']._serialized_end=224
  _globals['_POWER']._serialized_start=226
  _globals['_POWER']._serialized_end=247
  _globals['_POWEREFFICIENCY']._serialized_start=249
  _globals['_POWEREFFICIENCY']._serialized_end=294
  _globals['_TEMPERATURE']._serialized_start=296
  _globals['_TEMPERATURE']._serialized_end=327
  _globals['_BASESPOINTS']._serialized_start=329
  _globals['_BASESPOINTS']._serialized_end=355
  _globals['_HOURS']._serialized_start=357
  _globals['_HOURS']._serialized_end=379
# @@protoc_insertion_point(module_scope)
