# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from custom_components.minez.bos.v1 import upgrade_pb2 as bos_dot_v1_dot_upgrade__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bos/v1/upgrade_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UpgradeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateAutoUpgradeConfig = channel.unary_unary(
                '/braiins.bos.v1.UpgradeService/UpdateAutoUpgradeConfig',
                request_serializer=bos_dot_v1_dot_upgrade__pb2.UpdateAutoUpgradeConfigRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_upgrade__pb2.UpdateAutoUpgradeConfigResponse.FromString,
                _registered_method=True)
        self.GetAutoUpgradeStatus = channel.unary_unary(
                '/braiins.bos.v1.UpgradeService/GetAutoUpgradeStatus',
                request_serializer=bos_dot_v1_dot_upgrade__pb2.GetAutoUpgradeStatusRequest.SerializeToString,
                response_deserializer=bos_dot_v1_dot_upgrade__pb2.GetAutoUpgradeStatusResponse.FromString,
                _registered_method=True)


class UpgradeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateAutoUpgradeConfig(self, request, context):
        """Allows en/disabling of AutoUpgrade feature
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAutoUpgradeStatus(self, request, context):
        """Returns the current AutoUpgrade configuration and status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UpgradeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateAutoUpgradeConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAutoUpgradeConfig,
                    request_deserializer=bos_dot_v1_dot_upgrade__pb2.UpdateAutoUpgradeConfigRequest.FromString,
                    response_serializer=bos_dot_v1_dot_upgrade__pb2.UpdateAutoUpgradeConfigResponse.SerializeToString,
            ),
            'GetAutoUpgradeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAutoUpgradeStatus,
                    request_deserializer=bos_dot_v1_dot_upgrade__pb2.GetAutoUpgradeStatusRequest.FromString,
                    response_serializer=bos_dot_v1_dot_upgrade__pb2.GetAutoUpgradeStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'braiins.bos.v1.UpgradeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('braiins.bos.v1.UpgradeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UpgradeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateAutoUpgradeConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.UpgradeService/UpdateAutoUpgradeConfig',
            bos_dot_v1_dot_upgrade__pb2.UpdateAutoUpgradeConfigRequest.SerializeToString,
            bos_dot_v1_dot_upgrade__pb2.UpdateAutoUpgradeConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAutoUpgradeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/braiins.bos.v1.UpgradeService/GetAutoUpgradeStatus',
            bos_dot_v1_dot_upgrade__pb2.GetAutoUpgradeStatusRequest.SerializeToString,
            bos_dot_v1_dot_upgrade__pb2.GetAutoUpgradeStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
